[build]
  publish = "dist" # La carpeta de salida de tu build de React (ej. 'dist' para Vite)
  command = "npm run build" # El comando para construir tu frontend

[functions]
  directory = "netlify/functions" # El directorio padre de tus funciones
  node_bundler = "esbuild" # Netlify usará esbuild para tus funciones JS/TS.


[[plugins]]
package = "@netlify/plugin-functions-install-core"