[build]
  publish = "dist" # O la carpeta donde Vite genera tu build (normalmente 'dist')
  command = "npm run build" # O tu comando de construcción de React

[functions]
  directory = "netlify/functions" # Directorio donde están tus funciones
  node_bundler = "esbuild"
  