[build]
  publish = "dist" # O la carpeta donde Vite genera tu build (normalmente 'dist')
  command = "npm run build" # O tu comando de construcción de React

[functions]
  directory = "netlify/functions" # El directorio padre de tus funciones
  node_bundler = "esbuild" # Netlify usará esbuild para tus funciones JS/TS